### Import Numpy


In [1]:
import numpy as np 

### Creating a Numpy array 

#### A numpy array of zeros

In [2]:
a = np.zeros(3)
print(a)
print(type(a[0]))
print(a.shape)

[0. 0. 0.]
<class 'numpy.float64'>
(3,)


#### A numpy array of ones 

In [3]:
a = np.ones(3)
print(a)
print(type(a[0]))
print(a.shape)

[1. 1. 1.]
<class 'numpy.float64'>
(3,)


#### An empty numpy array 

In [4]:
a = np.empty(3)
a

array([1., 1., 1.])

#### Creating Array using linspace 
* Quite useful if you are making a plot and need an axis

In [5]:
a = np.linspace(2, 10, 5)     # From 2 to 10, with 5 elements 
a

array([ 2.,  4.,  6.,  8., 10.])

#### Numpy array from a python list

In [6]:
a = np.array([ 2, 4, 5 ,8])
a

array([2, 4, 5, 8])

In [7]:
a_list = [[1,2,3,4,5], [9,7,5,3,2]]
a = np.array(a_list)
print(type(a))
a

<class 'numpy.ndarray'>


array([[1, 2, 3, 4, 5],
       [9, 7, 5, 3, 2]])

#### Creating a Random Array 

In [8]:
np.random.seed(0)
a = np.random.randint(4, size = 6)   # 6 random int numbers from [0 to 4)
a

array([0, 3, 1, 0, 3, 3])

### Change shape of the numpy arary 


In [9]:
z = np.zeros(10)
print(z)
print(z.shape)

#
z.shape = (5,2)
print(z)
print(z.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
(5, 2)


### Accessing elements of NumPy Array 

In [10]:
z = np.array([1,3,5,7,9,8,6,4,2,0])

print(z[0])    # 0th Element  
 
print(z[0:3])  # From index [0 to 3) 

print(z[-1])   # -1 refers to last element OR 1st element from the end 

print(z[-4])   # 4th element from the end
 
print(z[-4:])  # last 4 elements 

print(z[::-1]) # All elements in reverse order


1
[1 3 5]
0
6
[6 4 2 0]
[0 2 4 6 8 9 7 5 3 1]


### Different Ways to Slice a NumPy Array 