## PyTorch 

- Scientific computing package  
- Replacement for NumPy to use the power of GPus 
- Deep learning research platform that provides maximum flexibility and speed 




In [1]:
import torch 

### Tensors 


PyTorch uses **Tensor** as its core data structure, which is similar to Numpy array. Tensors provide acceleration of various mathematical operations. These operations when carried out in a large number in Deep Learning make a huge difference in speed.

Tensor is simply a fancy name given to matrices. A scalar value is represented by a 0-dimensional Tensor. Similarly a column/row matrix using a 1-D Tensor and so on. 

#### Creating Tensors

In [11]:
# Create a tensor with just ones 

a = torch.ones(5)
print(a)


# Create a tensor with just zeros 

b = torch.zeros(5)
print(b)


# Create a tensor with custom values

c = torch.Tensor([1, 3, 5, 7, 9])
print(c)

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])
tensor([1., 3., 5., 7., 9.])


In [21]:
# Tensors of Higher dimension: 

# torch.zeros(Rows, Columns) 
d = torch.zeros(3,2)
print(d)


e = torch.ones(2,5)
print(e)


f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(f)


# 3D Tensor
g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(g)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [22]:
# find out shape of the tensor 

print(e.shape)

print(f.shape)
 
print(g.shape)


torch.Size([2, 5])
torch.Size([2, 2])
torch.Size([2, 2, 2])


#### Accessing element in a 1D Tensor aka vector

In [23]:
print(c[2])

tensor(5.)


#### Accessing element in a higher dimension Tensor 

To access one particular element in a tensor, we will need to specify indices equal to the dimension of the tensor. 

In [25]:
# All indices starting from 0
 
# Get element at row 1, column 0
print(f[1,0])

# We can also use the following
print(f[1][0])
 
# Similarly for 3D Tensor
print(g[1,0,0])
print(g[1][0][0])
 


tensor(3.)
tensor(3.)
tensor(5.)
tensor(5.)


In [36]:
# If you want to access one entire row in a 2D tensor, the syntax is same as NumPy 

# All elements 
print(f[:])

# All elements from index 1 to 2 (inclusive) 
print(c[1:3])

# All elements till index 3 (exclusive)
print(c[:3])

# All elements till the last (exclusive)
print(c[:-1])





tensor([[1., 2.],
        [3., 4.]])
tensor([3., 5.])
tensor([1., 3., 5.])
tensor([1., 3., 5., 7.])


In [34]:
c[:-1]

tensor([1., 3., 5., 7.])